name: multi_dropdown
version: 0.0.1
publish_to: 'none'
description: Local lightweight multi-select dropdown widget.

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
